Repository andrew-jolley/lecture-logger, pull requests merged in 2025-09, with the labels that each got.

#17 Splash Screen
  .DS_Store
  cleanup-install.bat
  index.html
  installer-script.nsh
  main.js
  package-lock.json
  package.json
  python-runtime/darwin-arm64/bin/python3
  python-runtime/linux-x64/bin/python3
  python/electron_settings.json
  renderer.js
  scripts/build-helper.js
  scripts/list-builds.js
  test-complete-flow.js
  test.xlsx
  ui/index.html
  ui/package.json
  ui/renderer.js
Labels: enhancement

#20 Updated Electron
  package-lock.json
  package.json
  python-runtime/darwin-arm64/bin/python3
  python/electron_settings.json
  renderer.js
  ui/renderer.js
Labels: enhancement

#26 4 UI window opens with scroll bars
  main.js
  python/electron_settings.json
Labels: bug, windows, P3

#36 Python - Dev to Main - Updates and Bug Fixes
  .gitignore
  Backend Files (Hidden)/log.txt
  OTJ_Automation.py
Labels: bug, Backend Python

#38 Python Dev to Main - Add error handling to all functions
  OTJ_Automation.py
Labels: bug, enhancement, Backend Python
